### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [jeremyfelt/dotfiles#43]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`README.md`](https://github.com/jeremyfelt/dotfiles/blob/d927e955bb65a83dec70cb3bf825628e510ff53e/README.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by jeremyfelt** [comment]
Fixed, thanks!
